services:
    reverseproxy:
        container_name: nginx_reverseproxy
        image: nginx:latest
        restart: unless-stopped
        volumes:
            -   ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            -   "80:80"
            -   "3080:3080"
        depends_on:
            -   api
        networks:
            -   mynetwork

    client:
        container_name: client
        build:
            context: ./client
        volumes:
            -   type: bind
                source: ./client
                target: /client
        env_file:
            - ./Docker/client/client-variables.env
        ports:
            -   "3000:3000"
        depends_on:
            -   api
        networks:
            -   react-express
        restart: always

    api:
        container_name: api
        build:
            context: ./api
        volumes:
            -   type: bind
                source: ./api
                target: /api
        env_file:
            - ./Docker/api/api-variable.env
        expose:
            - "3080"
        depends_on:
            - mongo
        networks:
            - mynetwork 
            - react-express
            - express-mongo
        restart: always

    mongo:
        container_name: mongo
        image: mongo
        expose:
            - "27017"
        networks:
            - express-mongo

networks:
    react-express:
    express-mongo:
    mynetwork:
